### ISSUE TITLE
Vote count integer overflow

### ISSUE THREAD

**Issue by bennetyee** [oasislabs/secret-ballot#17]
https://github.com/oasislabs/secret-ballot/blob/9294f5a3dc13d129e477c7862476c028acb30aa2/contracts/confidential_SecretBallot.sol#L17

The `votesReceived` mapping goes from candidates (`bytes32`) to `uint16`.  It is pretty easy to wrap around 65536 votes.  Maybe `uint32` instead?  And detect overflow in L32?  Same issue for `totalVotes`.

**Comment by willscott** [comment]
Should be addressed by #28
